name: Build

on: [push, pull_request]

jobs:
    build:
      runs-on: ubuntu-latest
      name: build
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.6
        - run:  |
            make build
            make test
            make vet
    release-bin:
      runs-on: ubuntu-latest
      name: release
      steps:
        - uses: actions/checkout@v2
        - name: Setup go
          uses: actions/setup-go@v2
          with:
            go-version: 1.16.6
        - name: build windows amd64
          run: GOOS=windows GOARCH=amd64 go build -o go-telegram-miner-bot-win-x64.exe cmd/go-telegram-miner-bot/main.go
        - name: build windows i386
          run: GOOS=windows GOARCH=386 go build -o go-telegram-miner-bot-win.exe cmd/go-telegram-miner-bot/main.go
        - name: build linux amd64
          run: GOOS=linux GOARCH=amd64 go build -o go-telegram-miner-bot-linux-x64 cmd/go-telegram-miner-bot/main.go
        - name: build linux i386
          run: GOOS=linux GOARCH=386 go build -o go-telegram-miner-bot-linux cmd/go-telegram-miner-bot/main.go
        - name: build linux arm
          run: GOOS=linux GOARCH=arm go build -o go-telegram-miner-bot-linux-arm cmd/go-telegram-miner-bot/main.go
        - name: build linux arm64
          run: GOOS=linux GOARCH=arm64 go build -o go-telegram-miner-bot-linux-arm64 cmd/go-telegram-miner-bot/main.go
        - name: build mac amd64
          run: GOOS=darwin GOARCH=amd64 go build -o go-telegram-miner-bot-mac-amd64 cmd/go-telegram-miner-bot/main.go
        - name: build mac arm64
          run: GOOS=darwin GOARCH=arm64 go build -o go-telegram-miner-bot-mac-arm64 cmd/go-telegram-miner-bot/main.go
        - name: Archive production artifacts Windows amd64
          uses: actions/upload-artifact@v2
          with:
            name: windows-amd64
            path: go-telegram-miner-bot-win-x64.exe
        - name: Archive production artifacts Windows i386
          uses: actions/upload-artifact@v2
          with:
            name: windows-i386
            path: go-telegram-miner-bot-win.exe
        - name: Archive production artifacts Linux amd64
          uses: actions/upload-artifact@v2
          with:
            name: linux-amd64
            path: go-telegram-miner-bot-linux-x64
        - name: Archive production artifacts Linux i386
          uses: actions/upload-artifact@v2
          with:
            name: linux-i386
            path: go-telegram-miner-bot-linux
        - name: Archive production artifacts Linux arm
          uses: actions/upload-artifact@v2
          with:
            name: linux-arm
            path: go-telegram-miner-bot-linux-arm
        - name: Archive production artifacts Linux arm64
          uses: actions/upload-artifact@v2
          with:
            name: linux-arm64
            path: go-telegram-miner-bot-linux-arm64
        - name: Archive production artifacts Mac amd64
          uses: actions/upload-artifact@v2
          with:
            name: mac-amd64
            path: go-telegram-miner-bot-mac-amd64
        - name: Archive production artifacts Mac arm64
          uses: actions/upload-artifact@v2
          with:
            name: mac-arm64
            path: go-telegram-miner-bot-mac-arm64